# Generated by Django 6.0.7 on 2026-07-15 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la leçon')),
                ('category', models.CharField(choices=[('SERENITY', 'Serenity Core'), ('STREET_TALK', 'Street Talk Series'), ('SLANGMAN', 'Slangman Guide')], default='SERENITY', max_length=20, verbose_name='Catégorie')),
                ('video_url', models.URLField(verbose_name='URL de la vidéo (YouTube/No-cookie)')),
                ('visual', models.ImageField(blank=True, null=True, upload_to='lessons/visuals/', verbose_name='Image illustrative (Optionnelle)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la leçon (Optionnelle)')),
                ('instructions_title', models.CharField(default="MISSION D'ACTIVATION", max_length=200, verbose_name='Titre de la mission')),
                ('instructions_text', models.TextField(verbose_name="Consignes de l'exercice")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_or_word', models.CharField(max_length=150, verbose_name='Mot, expression ou concept')),
                ('definition_or_content', models.TextField(verbose_name='Définition ou explication')),
                ('example', models.TextField(blank=True, null=True, verbose_name="Exemple d'utilisation (Optionnel)")),
                ('card_visual', models.ImageField(blank=True, null=True, upload_to='lessons/cards/', verbose_name='Visuel de la carte (Optionnel)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='courses.lesson', verbose_name='Leçon associée')),
            ],
            options={
                'verbose_name': 'Carte interactive',
                'verbose_name_plural': 'Cartes interactives',
            },
        ),
    ]
