# Generated by Django 6.0.6 on 2026-07-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_embed_code',
            field=models.TextField(blank=True, help_text="Collez ici l'intégralité du code d'intégration (ex: <iframe ...></iframe>) fourni par YouTube ou Vimeo.", null=True, verbose_name="Code d'intégration de la vidéo (Iframe/Embed)"),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='instructions_title',
            field=models.CharField(default="MISSION D'ACTIVATION", max_length=300, verbose_name='Titre de la mission'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Titre de la leçon'),
        ),
    ]
